# Generated by Django 5.0.6 on 2025-01-26 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoRequisite',
            fields=[
                ('corequisite_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('user_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_level_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='appCourseWare.userlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('class_time', models.CharField(max_length=100)),
                ('exam_time', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('remaining_capacity', models.IntegerField()),
                ('corequisites', models.ManyToManyField(related_name='corequired_for', through='appCourseWare.CoRequisite', to='appCourseWare.course')),
            ],
        ),
        migrations.AddField(
            model_name='corequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corequisites_set', to='appCourseWare.course'),
        ),
        migrations.AddField(
            model_name='corequisite',
            name='required_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_corequisites', to='appCourseWare.course'),
        ),
        migrations.CreateModel(
            name='CourseClassroom',
            fields=[
                ('course_classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classrooms', to='appCourseWare.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classrooms', to='appCourseWare.course')),
            ],
            options={
                'unique_together': {('course', 'classroom')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='classrooms',
            field=models.ManyToManyField(related_name='courses', through='appCourseWare.CourseClassroom', to='appCourseWare.classroom'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='appCourseWare.department'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='appCourseWare.department'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='appCourseWare.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='appCourseWare.instructor'),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('prerequisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_set', to='appCourseWare.course')),
                ('required_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_prerequisites', to='appCourseWare.course')),
            ],
            options={
                'unique_together': {('course', 'required_course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='required_for', through='appCourseWare.Prerequisite', to='appCourseWare.course'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('major', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('max_units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('admission_year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='appCourseWare.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='appCourseWare.student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='corequisite',
            unique_together={('course', 'required_course')},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='appCourseWare.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='appCourseWare.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
