# Generated by Django 5.0.6 on 2025-01-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCourseWare.classroom'),
        ),
    ]
