# Generated by Django 5.0.6 on 2025-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0002_alter_student_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(choices=[(1403, 1403), (1402, 1402), (1401, 1401), (1400, 1400), (1399, 1399), (1398, 1388)], default=1403),
        ),
    ]
