# Generated by Django 5.0.6 on 2025-01-28 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0002_alter_course_classroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Majors',
            new_name='Major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='max_units',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقا ۱۰ رقم باشد.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به فرم +98XXXXXXXXXX باشد.', regex='^\\+98\\d{10}$')]),
        ),
    ]
