# Generated by Django 5.1.4 on 2025-02-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0003_alter_student_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(error_messages={'unique': 'این نام دپارتمان قبلاً ثبت شده است'}, max_length=100, unique=True, verbose_name='نام دپارتمان'),
        ),
    ]
