# Generated by Django 5.0.6 on 2025-01-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0004_remove_course_remaining_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'در حال گذراندن'), ('dropped', 'افتاده'), ('withdrawed', 'حذف اضطراری'), ('completed', 'گذرانده')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day_of_week',
            field=models.CharField(choices=[('SAT', 'شنبه'), ('SUN', 'یکشنبه'), ('MON', 'دوشنبه'), ('TUE', 'سه\u200cشنبه'), ('WED', 'چهارشنبه')], max_length=3),
        ),
    ]
