# Generated by Django 5.0.6 on 2025-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0004_alter_department_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
