# Generated by Django 5.0.6 on 2025-01-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0005_alter_student_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCourseWare.major'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('enrolled', 'ثبت نام شده'), ('pending', 'انتظار'), ('withdrawn', 'حذف اضطراری'), ('completed', 'گذرانده')], max_length=20),
        ),
    ]
