# Generated by Django 5.0.6 on 2025-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0005_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_date',
            field=models.CharField(default='Sat', help_text='یکی یا دو روز از شنبه تا چهارشنبه را انتخاب کنید. (مثال: Sat,Mon)', max_length=23, verbose_name='روزهای برگزاری کلاس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_time',
            field=models.CharField(choices=[('8:00-10:00', '8:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00')], max_length=11, verbose_name='زمان برگزاری کلاس'),
        ),
    ]
