# Generated by Django 5.0.6 on 2025-02-04 19:54

import appCourseWare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0006_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_date',
            field=models.CharField(help_text='حداکثر 2 روز را با کاما جدا کنید (مثال: Sat,Mon)', max_length=23, validators=[appCourseWare.models.Course.validate_max_two_days], verbose_name='روزهای برگزاری کلاس'),
        ),
    ]
