# Generated by Django 5.0.6 on 2025-01-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0006_course_class_date_alter_course_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
    ]
