# Generated by Django 5.0.6 on 2025-02-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0007_alter_course_class_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='enrollment_date',
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn'), ('passed', 'Passed'), ('failed', 'Failed')], default='enrolled', max_length=20),
        ),
    ]
