# Generated by Django 5.0.6 on 2025-02-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0008_remove_studentcourse_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
