# Generated by Django 5.0.6 on 2025-01-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0009_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
    ]
