# Generated by Django 5.0.6 on 2025-01-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCourseWare', '0010_remove_course_capacity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
